[package]
name = "asahi-bless"
version = "0.4.4-neo.1"
edition = "2021"
license = "MIT"
description = "A tool to select active boot partition on ARM Macs"
homepage = "https://github.com/aurora-silicon/asahi-bless"
repository = "https://github.com/aurora-silicon/asahi-bless"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = "1"
gpt = "3"
clap = { version = "4.5", features = ["derive"] }

[dependencies.apple-nvram]
path = "../apple-nvram"
version = "0.3"
